### PR TITLE
Pham van khanh/final version

### PR DESCRIPTION
**Pull request by heefish**
- Group each component into a folder to increase readability
- Use CSS modules as the styling solution: avoid style conflict by scoping the CSS locally
- Use debounce function to avoid unnecessary API calls
- Replace named function with arrow function to avoid binding **this**
- Memmoize handlers with **useCallback** and remove all inline handlers to increase the perfomance
- KI-01: Compare the **Request time** with **Last request time** so we can determine which **results** to set to state
- KI-02: Add a loading spinner to input component. P/s: I have a another idea that fetch all items on component' mounting so we can implement the search on Front-end. But I don't know if it's legal or not

### CODE REVIEW

**Comment by heefish** [comment]
@longtran-pops I've installed node-sass to use SCSS in project. It is legal? Thank you.

**Comment by longtran-pops** [comment]
Hi @khanhpv0305 ,
Sorry but your PR come quite late. The deadline is yesterday morning. So, I consider your PR is an invalid PR.

**Comment by heefish** [comment]
Hi @longtran-pops
Sorry I didn't receive any information about the deadline exact time. The only thing that I have is "Thời hạn là 3 ngày".
Although my test has failed, I'm very excited to know how to do it correctly. Thank you very much :D

**Comment by longtran-pops** [comment]
Hi @khanhpv0305,
"Thời hạn là 3 ngày" is about 3 days since I added you to the repository which mean from 17/6.
We have given you a deadline to test how you organize your time to handle such kind of tasks, it's also about how you communicate with us when there're something unclear to you.

About your solution, I have reviewed it. 

`KI-01` is a common problem a.k.a `Race Condition`. There're 2 common ways to solve this: 
1. Debounce/Throttle requests and cancel invalid requests => If requests don't need to be processed in sequence
2. Add requests to the queues and process one by one => If requests must be processed in sequence
Autocomplete issue can be solved with 1st way, and that's what you have done so far.

`KI-02` is an open questions, there're no common way to solve this. There're many ways to solve one side of the issue and leave the other sides. For example, pre-fetching potential data, caching last fews requests, offline-data....

Thanks

**Pull request closed without merging**
