### PR TITLE
Minhle/final version

### PR DESCRIPTION
**Pull request by minhld205**
- Solved: **KI1** & **KI2**
- No using libs or framwork
- CSS style for desktop & mobile.
- Refactor not too much file. (I think its OK.)

### CODE REVIEW

**Comment by longtran-pops** [comment]
Hi @minhld205,
The deadline is yesterday morning. So, I considered this is an invalid PR.

**Comment by minhld205** [comment]
Sorry anh,
Nhưng vì cv e hiện tại cũng bận. E nghĩ là 3 ngày kể từ ngày e accept vào source là hợp lý hơn nên vì thế anh có thể xem xét giúp em trường hợp này.
Cảm ơn anh.

**Comment by longtran-pops** [comment]
Hi @minhld205,

I can understand your situation. We also have problem with daily tasks too. Managing your time and tasks are also part of the tests. So, I can't accept any exception which will not be fair to others who follow the timeline.

Thanks

**Comment by minhld205** [comment]
Hi a,
Thank you for let me know. Hope see you next time.

**Pull request closed without merging**
